### ISSUE TITLE
Question: difference from libavc

### ISSUE THREAD

**Issue by DCNick3** [ittiam-systems/lib264#8]
This project seem to have a significant code overlap with https://github.com/ittiam-systems/libavc

libavc seems to be used in AOSP and comes with an encoder and decoder, while this repository has only a decoder, with some additional "plugins": an ffmpeg plugin providing browser.

From what I gather, the actual decoder code is virtually the same. What is the reason between split then?

If I only need a decoder, am I better off using this repo, lib264?

**Comment by IttiamVijayakumarGR** [comment]
Yes, this repo is mainly to enable integration of H264 Decoder into systems beyond AOSP. Licensing terms are different compared to AOSP and code base supports plugins like FFmpeg, Browser Plugin with WASM build.
Currently the repo has support for H264 Decoder.
